# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Bazel Build (Linux)
permissions:
  contents: read
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_call:
jobs:
  linux-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - bazel-config: bl-x86_64-linux
            bazel-build-target: "//score/..."
            bazel-test-target: >-
              //score/...
              -//score/language/safecpp/aborts_upon_exception:abortsuponexception_toolchain_test
          - bazel-config: bl-aarch64-linux
            bazel-build-target: >-
              //score/result/...
              //score/filesystem/...
            bazel-test-target: >-
              //score/result/...
              //score/filesystem/...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.job }}_${{ matrix.bazel-config }}
          repository-cache: true
          cache-save: ${{ github.event_name == 'push' }}
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt install -y qemu-user
      - name: Bazel Build
        run: |
          bazel build --config ${{ matrix.bazel-config }} -- ${{ matrix.bazel-build-target }}
      - name: Bazel Test
        run: |
          bazel test --config ${{ matrix.bazel-config }} -- ${{ matrix.bazel-test-target }}
