# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Nightly Build & Test baselibs
# This workflow runs Bazel build and test every 24 hours at 01:00h.

name: Nightly Build & Test (baselibs components)
on:
  schedule:
    - cron: '0 1 * * *' # Runs at 01:00h every day
  workflow_dispatch:

jobs:
  call_jobs:
    uses: ./.github/workflows/jobs.yml
    with:
      build_type: nightly